<script src="{{ asset('libbackend/assets/global/plugins/jquery/jquery-1.11.1.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/jquery/jquery-migrate-1.2.1.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/jquery-ui/jquery-ui-1.11.2.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/gsap/main-gsap.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/bootstrap/js/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('libbackend/assets/global/plugins/jquery-cookies/jquery.cookies.min.js') }}"></script> <!-- Jquery Cookies, for theme -->
<script src="{{ asset('libbackend/assets/global/plugins/jquery-block-ui/jquery.blockUI.min.js') }}"></script> <!-- simulate synchronous behavior when using AJAX -->
<script src="{{ asset('libbackend/assets/global/plugins/bootbox/bootbox.min.js') }}"></script> <!-- Modal with Validation -->
<script src="{{ asset('libbackend/assets/global/plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js') }}"></script> <!-- Custom Scrollbar sidebar -->
<script src="{{ asset('libbackend/assets/global/plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js') }}"></script> <!-- Show Dropdown on Mouseover -->
<script src="{{ asset('libbackend/assets/global/plugins/charts-sparkline/sparkline.min.js') }}"></script> <!-- Charts Sparkline -->
<script src="{{ asset('libbackend/assets/global/plugins/retina/retina.min.js') }}"></script> <!-- Retina Display -->
<script src="{{ asset('libbackend/assets/global/plugins/select2/select2.min.js') }}"></script> <!-- Select Inputs -->
<script src="{{ asset('libbackend/assets/global/plugins/icheck/icheck.min.js') }}"></script> <!-- Checkbox & Radio Inputs -->
<script src="{{ asset('libbackend/assets/global/plugins/backstretch/backstretch.min.js') }}"></script> <!-- Background Image -->
<script src="{{ asset('libbackend/assets/global/plugins/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script> <!-- Animated Progress Bar -->
<script src="{{ asset('libbackend/assets/global/plugins/charts-chartjs/Chart.min.js') }}"></script>
{{-- <script src="{{ asset('libbackend/assets/global/js/builder.js') }}"></script> <!-- Theme Builder --> --}}
<script src="{{ asset('libbackend/assets/global/js/sidebar_hover.js') }}"></script> <!-- Sidebar on Hover -->
<script src="{{ asset('libbackend/assets/global/js/application.js') }}"></script> <!-- Main Application Script -->
<script src="{{ asset('libbackend/assets/global/js/plugins.js') }}"></script> <!-- Main Plugin Initialization Script -->
<script src="{{ asset('libbackend/assets/global/js/widgets/notes.js') }}"></script> <!-- Notes Widget -->
<script src="{{ asset('libbackend/assets/global/js/quickview.js') }}"></script> <!-- Chat Script -->
<script src="{{ asset('libbackend/assets/global/js/pages/search.js') }}"></script> <!-- Search Script -->
<script src="{{ asset('libbackend/assets/global/plugins/bootstrap-loading/lada.min.js') }}"></script> <!-- Search Script -->

